use std::collections::HashMap;

pub fn models() -> HashMap<String, String> {
    HashMap::from([
        (
            String::from("tiny.en"),
            String::from("Systran/faster-whisper-tiny.en"),
        ),
        (
            String::from("tiny"),
            String::from("Systran/faster-whisper-tiny"),
        ),
        (
            String::from("base.en"),
            String::from("Systran/faster-whisper-base.en"),
        ),
        (
            String::from("base"),
            String::from("Systran/faster-whisper-base"),
        ),
        (
            String::from("small.en"),
            String::from("Systran/faster-whisper-small.en"),
        ),
        (
            String::from("small"),
            String::from("Systran/faster-whisper-small"),
        ),
        (
            String::from("medium.en"),
            String::from("Systran/faster-whisper-medium.en"),
        ),
        (
            String::from("medium"),
            String::from("Systran/faster-whisper-medium"),
        ),
        (
            String::from("large-v1"),
            String::from("Systran/faster-whisper-large-v1"),
        ),
        (
            String::from("large-v2"),
            String::from("Systran/faster-whisper-large-v2"),
        ),
        (
            String::from("large-v3"),
            String::from("Systran/faster-whisper-large-v3"),
        ),
        (
            String::from("large"),
            String::from("Systran/faster-whisper-large-v3"),
        ),
        (
            String::from("distil-large-v2"),
            String::from("Systran/faster-distil-whisper-large-v2"),
        ),
        (
            String::from("distil-medium.en"),
            String::from("Systran/faster-distil-whisper-medium.en"),
        ),
        (
            String::from("distil-small.en"),
            String::from("Systran/faster-distil-whisper-small.en"),
        ),
        (
            String::from("distil-large-v3"),
            String::from("Systran/faster-distil-whisper-large-v3"),
        ),
        (
            String::from("distil-large-v3.5"),
            String::from("distil-whisper/distil-large-v3.5-ct2"),
        ),
        (
            String::from("large-v3-turbo"),
            String::from("mobiuslabsgmbh/faster-whisper-large-v3-turbo"),
        ),
        (
            String::from("turbo"),
            String::from("mobiuslabsgmbh/faster-whisper-large-v3-turbo"),
        ),
    ])
}
